
name: 'Missing Bot'
description: 'Use when you get a Missing Bot error'
title: 'Missing Character'
labels: 'missing character'

body: 
- type: input
  id: cid
  attributes:
    label: 'Error CID'
    description: "The CID in the error message"
  validations:
    required: true

